// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {config} from '../models';
import {history} from '../models';
import {runner} from '../models';

export function ApplyWindowScale():Promise<void>;

export function Catalog():Promise<Array<catalog.Item>>;

export function ClearHistory():Promise<void>;

export function CurrentLang():Promise<string>;

export function DeleteRuns(arg1:Array<string>):Promise<void>;

export function FontCSS():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetHistory():Promise<Array<history.Entry>>;

export function GetRun(arg1:string):Promise<runner.Report>;

export function ListFonts():Promise<Array<string>>;

export function Presets():Promise<Record<string, Array<string>>>;

export function RunCheck():Promise<runner.Report>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetLang(arg1:string):Promise<void>;

export function SetServices(arg1:Array<string>,arg2:Array<catalog.Custom>):Promise<void>;

export function SetTab(arg1:string):Promise<void>;

export function Version():Promise<string>;
