// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyWindowScale() {
  return window['go']['main']['App']['ApplyWindowScale']();
}

export function CancelCheck() {
  return window['go']['main']['App']['CancelCheck']();
}

export function Catalog() {
  return window['go']['main']['App']['Catalog']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CurrentLang() {
  return window['go']['main']['App']['CurrentLang']();
}

export function DeleteRuns(arg1) {
  return window['go']['main']['App']['DeleteRuns'](arg1);
}

export function FontCSS() {
  return window['go']['main']['App']['FontCSS']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetRun(arg1) {
  return window['go']['main']['App']['GetRun'](arg1);
}

export function ListFonts() {
  return window['go']['main']['App']['ListFonts']();
}

export function Presets() {
  return window['go']['main']['App']['Presets']();
}

export function RunCheck() {
  return window['go']['main']['App']['RunCheck']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function SetServices(arg1, arg2) {
  return window['go']['main']['App']['SetServices'](arg1, arg2);
}

export function SetTab(arg1) {
  return window['go']['main']['App']['SetTab'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
